config/routes.rb
PostitTemplate::Application.routes.draw do
  root to: 'posts#index'

  get '/register', to: 'users#new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'

  resources :posts, except: [:destroy] do
    member do
      post 'vote'
    end

    resources :comments, only: [:create] do
      member do
        post 'vote'
      end
    end
  end

  resources :categories, only: [:new, :create, :show]
  resources :users, except: [:destroy, :index, :new]
end

app/models/category.rb
class Category < ActiveRecord::Base
  include Sluggable

  has_many :post_categories
  has_many :posts, through: :post_categories

  validates :name, presence: true

  sluggable_column :name
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  include Voteable

  belongs_to :user
  belongs_to :post

  validates :body, presence: true

  
end

app/models/post.rb
class Post < ActiveRecord::Base
  include Voteable
  include Sluggable

  belongs_to :user
  has_many :comments
  has_many :post_categories
  has_many :categories, through: :post_categories

  validates :title, presence: true
  validates :url, presence: true, uniqueness: true
  validates :description, presence: true

  sluggable_column :title

end

app/models/post_category.rb
class PostCategory < ActiveRecord::Base
  belongs_to :post
  belongs_to :category
end

app/models/user.rb
class User < ActiveRecord::Base
  include Sluggable

  has_many :posts
  has_many :comments
  has_many :votes

  has_secure_password validations: false

  validates :username, presence: true, uniqueness: true
  validates :password, presence: true, on: :create, length: {minimum: 6}

  sluggable_column :username

  def admin?
    self.role == "admin"
  end
end

app/models/vote.rb
class Vote < ActiveRecord::Base
  belongs_to :user
  belongs_to :voteable, polymorphic: true

  validates_uniqueness_of :user, scope: :voteable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user, :logged_in?

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user
  end

  def require_user
    if !logged_in?
      flash[:error] = "You must be logged in to do that."
      redirect_to root_path
    end
  end

  def require_admin
    access_denied unless logged_in? && current_user.admin?
  end

  def access_denied
    flash[:error] = "You do not have permission to do that."
    redirect_to root_path
  end    

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :require_user, only: [:new, :create]
  before_action :require_admin, only: [:new, :create]

  def show
    @category = Category.find_by(slug: params[:id])
  end

  def new
    @category = Category.new
  end
  
  def create
    @category = Category.new(category_params)

    if @category.save
      flash[:notice] = "Category created successfully!"
      redirect_to posts_path
    else
      render :new
    end
  end

  private

  def category_params
    params.require(:category).permit(:name)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :require_user

  def create
    @post = Post.find_by(slug: params[:post_id])
    @comment = @post.comments.build(params.require(:comment).permit(:body))
    @comment.user = current_user

    if @comment.save
      flash[:notice] = "Comment saved!"
      redirect_to post_path(@post)
    else
      render 'posts/show'
    end
  end

  def vote
    @comment = Comment.find(params[:id])
    @vote = Vote.create(voteable: @comment, vote: params[:vote], user: current_user)
    
    respond_to do |format|
      format.html do
        if @vote.valid?
          flash[:notice] = "Thanks for your vote!"
        else
          flash[:error] = "You already voted for this comment."
        end  
        redirect_to :back
      end
      format.js
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :vote]
  before_action :require_user, except: [:show, :index]
  before_action :require_admin_or_creator, only: [:edit, :update]

  def index
    @posts = Post.all.sort_by{|post| post.vote_total}.reverse
  end

  def show
    @comment = Comment.new
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.user = current_user

    if @post.save
      flash[:notice] = "Post created successfully!"
      redirect_to posts_path
    else #validation error
      render :new
    end
  end

  def edit
  end

  def update
    if @post.update(post_params)
      flash[:notice] = "Post updated successfully!"
      redirect_to posts_path
    else #validation error
      render :edit
    end
  end

  def vote
    @vote = Vote.create(voteable: @post, vote: params[:vote], user: current_user)
    
    respond_to do |format|
      format.html do
        if @vote.valid?
          flash[:notice] = "Thanks for your vote!" 
        else
          flash[:notice] = "You already voted for this post."
        end
        redirect_to :back
      end
      format.js
    end

  end

  private

  def post_params
    params.require(:post).permit(:title, :url, :description, category_ids: [])
  end

  def set_post
    @post = Post.find_by(slug: params[:id])
  end

  def require_admin_or_creator
    access_denied unless logged_in? && (current_user.admin? || @post.user == current_user)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by(username: params[:username])
    
    if user && user.authenticate(params[:password]) 
      session[:user_id] = user.id
      flash[:notice] = "Welcome back, #{user.username}!"
      redirect_to posts_path
    else
      flash[:error] = "Incorrect username or password. Please try again."
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:notice] = "You are now logged out."
    redirect_to posts_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update]
  before_action :require_user, only: [:edit, :update]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      flash[:notice] = "Welcome to Postit, #{@user.username}!"
      session[:user_id] = @user.id
      redirect_to posts_path
    else
      render :new
    end
  end

  def show
    
  end

  def edit

  end

  def update
    if @user.update(user_params)
      flash[:notice] = "Profile updated successfully!"
      redirect_to user_path(@user)
    else #validation error
      render :edit
    end
  end

  private
  
  def user_params
    params.require(:user).permit(:username, :password, :time_zone)
  end

  def set_user
    @user = User.find_by(slug: params[:id])
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
  def fix_url(str)
    str.starts_with?('http://') ? str : "http://#{str}"
  end

  def fix_date(date)
    if logged_in? && !current_user.time_zone.blank?
      date = date.in_time_zone(current_user.time_zone)
    end

    date.strftime("%l:%M%P %Z on %-m/%d/%Y")
  end
end

app/views/categories/_category.html.erb
<span class='badge'><%= link_to category.name, category_path(category) %></span>

app/views/categories/new.html.erb
<%= render 'shared/content_title', title: "New Category" %>

<%= render 'shared/error', obj: @category %>

<%= form_for @category do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <br/>
  <%= f.submit "Create Category", class: "btn btn-primary" %>
<% end %>

app/views/categories/show.html.erb
<% header = link_to("All Posts", posts_path) + " &raquo; #{@category.name}".html_safe %>
<%= render 'shared/content_title', title: header %>

<% if @category.posts.empty? %>
  <p>Looks like there are no posts in this category yet.</p>
  <%= link_to "Create Post", new_post_path %>
<% else %>
  <% @category.posts.each do |post| %>
    <%= render 'posts/post', post: post %>
  <% end %>
<% end %>

app/views/comments/_comment.html.erb
<% user_page ||= false %>

<div class="row">
  <div class="span0 well text-center">
    <% if logged_in? %>
      <%= link_to vote_post_comment_path(comment.post, comment, vote: true), method: "post", remote: true do %>
        <i class="icon-arrow-up"></i>
      <% end %>
    <% end %>
    <br/>
    <span id="comment_<%= comment.id %>_votes"><%= comment.vote_total %> votes</span>
    <br/>
    <% if logged_in? %>
      <%= link_to vote_post_comment_path(comment.post, comment, vote: false), method: "post", remote: true do %>
        <i class="icon-arrow-down"></i>
      <% end %>
    <% end %>  
  </div>

  <div class='span8 well'>
    <p>
      <em><%= comment.body %></em>
    </p>
    <p>
      <% if user_page %>
       <span class='quiet'>on </span><%= link_to comment.post.title, post_path(comment.post) %>
      <% else %>
        <span class='quiet'>by </span><%= link_to comment.user.username, user_path(comment.user) %>
      <% end %>
      <small>at <%= comment.created_at %></small>
    </p>
  </div>
</div>

app/views/comments/vote.js.erb
<% if @vote.valid? %>
  $("#comment_<%= @comment.id %>_votes").html("<%= @comment.vote_total %> votes");
<% else %>
  alert('You already voted on this comment.');
<% end %>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
      <a class="close" data-dismiss="alert">&#215;</a>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<ul class="nav">
  <li>
    <%= link_to "Postit!", root_path, :class => 'brand' %>
  </li>
  <li>
    <%= link_to  '' %>
  </li>
</ul>
<!-- categories dropdown -->
<div class='btn-group nav_item'>
  <%= link_to '#', class: 'btn btn-small dropdown-toggle', 'data-toggle' => 'dropdown' do %>
    Categories <span class="caret"></span>
  <% end %>
  <ul class="dropdown-menu">
    <% Category.all.each do |category| %>
      <li><%= link_to category.name, category_path(category) %></li>
    <% end %>
    <% if logged_in? && current_user.admin? %>
      <li class="divider"></li>
      <li>
        <%= link_to(new_category_path) do %>
          <i class="icon-plus"></i>
          New Category
        <% end %>
      </li>
    <% end %>
  </ul>
</div>
<!-- logged in menu items -->
<% if logged_in? %>
  <div class='nav_item'>
    <%= link_to 'New Post', new_post_path, class: 'btn btn-success btn-small' %>
  </div>
  <!-- profile and logout dropdown -->
  <div class='btn-group nav_item'>
    <%= link_to '#', class: 'btn btn-small dropdown-toggle', 'data-toggle' => 'dropdown' do %>
      <%= current_user.username %> <span class="caret"></span>
    <% end %>
    <ul class="dropdown-menu">
      <li>
        <%= link_to edit_user_path(current_user) do %>
        <i class="icon-pencil"></i>
        Edit Profile
        <% end %>
      </li>
      <li>
        <%= link_to user_path(current_user) do %>
        <i class="icon-user"></i>
        View Profile
        <% end %>
      </li>
      <li class="divider"></li>
      <li>
        <%= link_to '/logout' do %>
          <i class="icon-off"></i>
          Logout
        <% end %>
      </li>
    </ul>
  </div>
<!-- not logged in menu items -->
<% else %>
  <div class='nav_item'>
    <%= link_to 'Register', '/register', class: 'btn btn-success btn-small' %>
  </div>
  <div class='nav_item'>
    <%= link_to 'Login', '/login', class: 'btn btn-small' %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!doctype html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Tealeaf Academy - Postit</title>
    <meta name="description" content="">
    <meta name="author" content="">
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= yield(:head) %>
  </head>
  <body>
    <header>
      <div class="navbar">
        <div class="navbar-inner">
          <div class="container">
            <%= render 'layouts/navigation' %>
          </div>
        </div>
      </div>
    </header>
    <div id="main" role="main">
      <div class="container">
         <div class="row">
          <div class="span12">
            <%= render 'layouts/messages' %>
            <%= yield %>
          </div>
        </div>
        <footer>
        </footer>
      </div> <!--! end of .container -->
    </div> <!--! end of #main -->
  </body>
</html>

app/views/posts/_form.html.erb
<%=  render 'shared/error', obj: @post %>

<%= form_for @post do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <br/>
  <%= f.label :url %>
  <%= f.text_field :url %>
  <br/>
  <%= f.label :description %>
  <%= f.text_area :description %>
  <br/>
  <div class="control-group">
    <%= f.collection_check_boxes :category_ids, Category.all, :id, :name do |checkbox| %>
      <% checkbox.label(class: "checkbox inline") {checkbox.check_box(class: "checkbox") + checkbox.text} %>
    <% end %>
  </div>
  <%= f.submit (@post.new_record? ? "Create Post" : "Update Post"), class: 'btn btn-primary' %>
<% end %>

app/views/posts/_post.html.erb
<div class='row'>
  <div class='span0 well text-center'>
    <% if logged_in? %>
      <%= link_to vote_post_path(post, vote: true), method: "post", remote: true do %>
        <i class='icon-arrow-up'></i>
      <% end %>
    <% end %>
    <br/>
    <span id="post_<%= post.id %>_votes"><%= post.vote_total %> votes</span>
    <br/>
    <% if logged_in? %>
      <%= link_to vote_post_path(post, vote: false), method: "post", remote: true do %>
        <i class='icon-arrow-down'></i>
      <% end %>
    <% end %>
  </div>
  <div class='span8 well'>
    <%= render post.categories %>
    <h4><%= link_to post.title, fix_url(post.url) %></h4>
    <p><%= post.description %></p>
    <p>
      <span class='quiet'>posted by </span><%= link_to post.user.username, user_path(post.user) %>
      <small> at <%= fix_date(post.created_at) %></small>
    </p>
    <small><%= link_to "#{post.comments.size} comments", post_path(post) %></small>
  </div>
</div>

app/views/posts/edit.html.erb
<h4>Edit Post</h4>

<%= render 'form' %>

app/views/posts/index.html.erb
<%= render 'shared/content_title', title: "All Posts" %>

<% @posts.each do |post| %>
  <%= render 'post', post: post %>
<% end %>

app/views/posts/new.html.erb
<div class="row">
  <div class="span8 well">
    <h4>New Post</h4>
    <%= render 'form' %>
  </div>
</div>

app/views/posts/show.html.erb
<p>
  <%= render @post.categories %>
</p>

<% if logged_in? %>
  <p class="pull-right">
    [<%= link_to "edit this post", edit_post_path(@post) %>]
  </p>
<% end %>

<%= render 'shared/content_title', title: @post.title %>

<p>
<%= @post.description %>
<hr/>
</p>

<% if logged_in? %>
  <h5>Add a Comment:</h5>
  <%= render 'shared/error', obj: @comment %>
  <%= form_for [@post, @comment] do |f| %>
    <%= f.label :body %>
    <%= f.text_area :body %>
    <br/>
    <%= f.submit "Create Comment", class: "btn btn-primary" %>
  <% end %>
<% end %>

<h5>Comments:</h5>

<% @post.comments.each do |comment| %>
  <%= render "comments/comment", comment: comment %>
<% end %>    

app/views/posts/vote.js.erb
<% if @vote.valid? %>
  $("#post_<%= @post.id %>_votes").html("<%= @post.vote_total %> votes");
<% else %>
  alert('You already voted on this post.');
<% end %>

app/views/shared/_content_title.html.erb
<p class='lead'>
  <%= title %>
  <hr/>
</p>

app/views/shared/_error.html.erb
<% if obj.errors.any? %> 
  <div class='alert alert-error'>
    <h5>Oops! There were some errors:</h5>
    <ul>
      <% obj.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/_form.html.erb
<div class="row">
  <div class="span8 well">
    <%= render 'shared/error', obj: @user %>
    <%= form_for @user do |f| %>
      <%= f.label :username %>
      <%= f.text_field :username %>
      <br/>
      <%= f.label :password %>
      <%= f.password_field :password %>
      <br/>
      <%= f.label :time_zone %>
      <%= f.time_zone_select :time_zone, ActiveSupport::TimeZone.us_zones, default: Time.zone.name %>
      <br/>
      <%= f.submit (@user.new_record? ? "Register" : "Save Profile"), class: 'btn btn-success' %>
    <% end %>
  </div>
</div>

app/views/users/edit.html.erb
<%= render 'shared/content_title', title: 'Edit Your Profile' %>

<%= render 'form' %>

app/views/users/new.html.erb
<%= render 'shared/content_title', title: "Register" %>

<%= render 'form' %>

app/views/users/show.html.erb
<%= render 'shared/content_title', title: "#{@user.username}'s Profile" %>

<div class="row">
  <div class="span8 well">
    <strong>Username: </strong> <%= @user.username %>
    <br/>
    <strong>Time Zone: </strong> <%= @user.time_zone %>
  </div>
</div>

<h5><%= @user.username %>'s Activity</h5>

<ul class="nav nav-tabs">
  <li class="<%= 'active' if params[:tab].nil? %>" >
    <%= link_to "Posts (#{@user.posts.count})", user_path(@user) %>
  </li>
  <li class="<%= 'active' if params[:tab] == 'comments' %>" >
    <%= link_to "Comments (#{@user.comments.count})", user_path(@user, tab: 'comments') %>
  </li>
</ul>

<% if params[:tab].nil? %>
  <% @user.posts.each do |post| %>
    <%= render post %>
  <% end %>
<% else %>
  <% @user.comments.each do |comment| %>
    <%= render comment, user_page: true %>
  <% end %>
<% end %>